const ProdutosPromocao=[
    {
        id: 1,
        image: "https://sambayexpress.com.br/api/static/product/27-1.jpeg",
        title: "Kit 3 figurinhas originais",
        detalhe: "Kit com 3 figurinhas originais do Zequinha de 1979. Diferentes e muito bem conservadas. Numeração aleatória. Da número 1 a 200. Observe bem as fotos, antes de comprar. Preço para 3 unidades (3 figurinhas). Veja, também, meus outros leilões de produtos diferenciados! Compre na Sambay! Aqui, conseguimos vender pelos melhores preços! Obrigado pela visita.",
        price: 'R$ 12,00',
        prazo: 'Em até 2X',
        tipo: 'Promoção',
    },
    {
        id: 2,
        image: "https://sambayexpress.com.br/api/static/product/151-1.jpeg",
        title: 'Caneca Zequinha no Carrinho de Rolimã',
        detalhe: "Caneca de porcelana de alta resistência, com capacidade de 325 ml. Elas são estampadas em qualidade fotográfica, com cores brilhantes de excelente qualidade e acabamento impecável. Alça e interior coloridas. A caneca mede 9,6 cm de altura e 8,2 cm de diâmetro.",
        price: 'R$ 59,90',
        prazo: 'Em até 2X',
        tipo: 'Promoção',
    },
    {
        id: 3,
        image: "https://sambayexpress.com.br/api/static/product/209-1.jpeg",
        title: 'Kit Canecas fig, 107 e fig, 47 do Zequinha',
        detalhe: "Kit com 2 canecas do Zequinha. Figurinha 107-Zequinha tomando cafézinho, cor disponível: laranja + Figurinha 47-Zequinha de Bicicleta, cor disponível: amarela. O kit de R$ 119,80 fica pelo de R$ 99,90. Aproveite e adquira já o seu kit.",
        price: 'R$ 99,90',
        prazo: 'Em até 3X',
        tipo: 'Promoção',
    },
    {
        id: 4,
        image: "https://sambayexpress.com.br/api/static/product/205-1.jpeg",
        title: 'Chaveiro Retangular do Zequinha',
        detalhe: "Chaveiro com uma estampa diferente do personagem Zequinha, ilustrado pelo artista Nilson Muller. Estampa em dupla face, com logo do personagem e com a ilustração andando de bicicleta.  Formato Retangular. Dimensões: 3,5 cm x 2,5 cm c/ Argola: 4,0 cm. Dimensões Aproximadas.",
        price: 'R$ 6,00',
        prazo: 'Em até 1X',
        tipo: 'Promoção',
    },
    {
        id: 5,
        image: "https://sambayexpress.com.br/api/static/product/248-1.jpeg",
        title: 'Ioiô Preto do Zequinha Clássico',
        detalhe: "Ioiô é um dos brinquedos mais antigos existentes. É constituído de dois discos de plástico, unidos no centro por um eixo no qual prende-se uma corda. O ioiô do Zequinha está disponível em 6 cores diferentes! Ioiô com a estampa da logo do Zequinha, e do perfil do personagem. Garanta já o seu! Dimensões: diâmetro de: 6 cm.",
        price: 'R$ 8,00',
        prazo: 'Em até 1X',
        tipo: 'Promoção',
    },
]

const ProdutosNovidades = [
    {
        id: 1,
        image: "https://sambayexpress.com.br/api/static/product/285-1.jpeg",
        title: "Botton do Zequinha - 5cm - Rosa",
        detalhe: "Lançamento! Botton colorido do Zequinha, na cor rosa (desenho do Zequinha apaixonado), com 5 cm de diâmetro. Excelente qualidade. feito em plástico especial, com 2 mm de espessura. Não desbota e nem enferruja. Veja os outros modelos disponíveis, na última foto! O modelo que será entregue é o do sticker apaixonado (fundo rosa). Observe bem as fotos, antes de comprar. Obrigado pela visita! E veja também nossos demais produtos do Zequinha: https://sambayexpress.com.br/shopping/16/products",
        price: 'R$ 8,00',
        prazo: 'Em até 1X',
        tipo: 'Lançamento',
    },
    {
        id: 2,
        image: "https://sambayexpress.com.br/api/static/product/214-1.jpeg",
        title: 'Cofrinho de Papelão Logo Zequinha Branco',
        detalhe: "O cofrinho do Zequinha, além de ser um ótimo artigo para decoração, serve para ensinar seus filhos a guardarem aquelas moedas que sobram no fundo do bolso, ou até mesmo as que vão se acumulando. Cor: branco. Cofrinho papelão 6 x 9,5 cm (Diâmetro x altura)",
        price: 'R$ 6,00',
        prazo: 'Em até 1X',
        tipo: 'Lançamento',
    },
    {
        id: 3,
        image: "https://sambayexpress.com.br/api/static/product/268-1.jpeg",
        title: 'Kit 3 figurinhas raras Bala Zequinha',
        detalhe: "Kit com 3 figurinhas raras da tradicional Bala Zequinha!!! Empacotadas por Zigmundo Zavadski! Altamente colecionáveis, as antigas e raras figurinhas da época das balas Zequinha agora estão disponíveis! Preço por 3 figurinhas aleatórias e não repetidas. Todas em muito bom estado de conservação e acomodadas em prático invólucro de acetato. Provável década de 1950. Veja bem as fotos, antes de comprar. No Sambay, vendemos pelos melhores preços. Veja, também, meus outros anúncios. Obrigado!",
        price: 'R$ 59,00',
        prazo: 'Em até 3X',
        tipo: 'Lançamento',
    },
    {
        id: 4,
        image: "https://sambayexpress.com.br/api/static/product/230-1.jpeg",
        title: 'Raro! As Histórias do Capitão Gralha',
        detalhe: "Chaveiro com uma estampa diferente do personagem Zequinha, ilustrado pelo artista Nilson Muller. Estampa em dupla face, com logo do personagem e com a ilustração andando de bicicleta.  Formato Retangular. Dimensões: 3,5 cm x 2,5 cm c/ Argola: 4,0 cm. Dimensões Aproximadas.",
        price: 'R$ 79,90',
        prazo: 'Em até 3X',
        tipo: 'Lançamento',
    },
    {
        id: 5,
        image: "https://sambayexpress.com.br/api/static/product/191-1.jpeg",
        title: 'Pacote de figurinhas do Zequinha',
        detalhe: "Pacote de figurinha Zequinha 40 anos, contendo 5 cromos cada envelope. Prepare-se para colecionar os cromos da coleção especial de 40 anos do Zequinha. Este álbum é ilustrado pelo artista Nilson Muller, que desenhou todas as 208 figurinhas, em comemoração aos 40 anos do personagem Zequinha. Colecione e acompanhe. A coleção tem 200 figurinhas normais e 8 figurinhas especiais metalizadas! O Álbum tem 24 páginas. Os pacotes serão enviados em cores mescladas. Visite nossa loja oficial e veja nossos demais produtos! Obrigado pela visita.",
        price: 'R$ 3,50',
        prazo: 'Em até 1X',
        tipo: 'Lançamento',
    },
]


export {ProdutosPromocao, ProdutosNovidades};